using Portfolio.Models.Enums;

namespace Portfolio.Helpers
{
    public static class MaterialIconHelper
    {
        public static string ToIconString(MaterialIcon icon) => icon switch
        {
            // Navigation & Arrows
            MaterialIcon.ArrowBack => "arrow_back",
            MaterialIcon.ArrowForward => "arrow_forward",
            MaterialIcon.ArrowDownward => "arrow_downward",
            MaterialIcon.ArrowUpward => "arrow_upward",
            MaterialIcon.ChevronRight => "chevron_right",
            MaterialIcon.ChevronLeft => "chevron_left",
            MaterialIcon.ExpandMore => "expand_more",
            MaterialIcon.ExpandLess => "expand_less",
            MaterialIcon.Menu => "menu",
            MaterialIcon.Close => "close",
            MaterialIcon.OpenInNew => "open_in_new",
            MaterialIcon.Flutter => "flutter",
            MaterialIcon.HTML => "html",
            MaterialIcon.CSS => "css",
            // Actions
            MaterialIcon.Check => "check",
            MaterialIcon.CheckCircle => "check_circle",
            MaterialIcon.Add => "add",
            MaterialIcon.Remove => "remove",
            MaterialIcon.Delete => "delete",
            MaterialIcon.Edit => "edit",
            MaterialIcon.Save => "save",
            MaterialIcon.Refresh => "refresh",
            MaterialIcon.Settings => "settings",
            MaterialIcon.Search => "search",
            MaterialIcon.FilterList => "filter_list",
            MaterialIcon.Sort => "sort",
            MaterialIcon.Download => "download",
            MaterialIcon.Upload => "upload",
            MaterialIcon.Share => "share",
            MaterialIcon.CopyAll => "copy_all",
            MaterialIcon.ContentPaste => "content_paste",
            MaterialIcon.Visibility => "visibility",
            MaterialIcon.VisibilityOff => "visibility_off",

            // Communication
            MaterialIcon.Email => "email",
            MaterialIcon.Chat => "chat",
            MaterialIcon.Notifications => "notifications",
            MaterialIcon.NotificationsActive => "notifications_active",
            MaterialIcon.Send => "send",
            MaterialIcon.Phone => "phone",
            MaterialIcon.LocationOn => "location_on",
            MaterialIcon.Language => "language",
            MaterialIcon.Public => "public",

            // Status & Feedback
            MaterialIcon.Info => "info",
            MaterialIcon.Warning => "warning",
            MaterialIcon.Error => "error",
            MaterialIcon.Success => "check_circle",
            MaterialIcon.Pending => "pending",
            MaterialIcon.HourglassEmpty => "hourglass_empty",
            MaterialIcon.CheckCircleOutline => "check_circle_outline",
            MaterialIcon.WarningAmber => "warning_amber",
            MaterialIcon.ErrorOutline => "error_outline",
            MaterialIcon.Cancel => "cancel",
            MaterialIcon.Block => "block",

            // Tech & Development
            MaterialIcon.Code => "code",
            MaterialIcon.Terminal => "terminal",
            MaterialIcon.Memory => "memory",
            MaterialIcon.Storage => "storage",
            MaterialIcon.Cloud => "cloud",
            MaterialIcon.CloudUpload => "cloud_upload",
            MaterialIcon.CloudDownload => "cloud_download",
            MaterialIcon.Database => "database",
            MaterialIcon.Server => "dns",
            MaterialIcon.Api => "api",
            MaterialIcon.Hub => "hub",
            MaterialIcon.NetworkNode => "network_node",
            MaterialIcon.Security => "security",
            MaterialIcon.Shield => "shield",
            MaterialIcon.Key => "key",
            MaterialIcon.Lock => "lock",
            MaterialIcon.LockOpen => "lock_open",
            MaterialIcon.BugReport => "bug_report",
            MaterialIcon.Build => "build",
            MaterialIcon.Engineering => "engineering",
            MaterialIcon.SmartToy => "smart_toy",
            MaterialIcon.Devices => "devices",
            MaterialIcon.Monitor => "monitor",
            MaterialIcon.Smartphone => "smartphone",
            MaterialIcon.Laptop => "laptop_chromebook",
            MaterialIcon.DesktopMac => "desktop_mac",
            MaterialIcon.Router => "router",
            MaterialIcon.Wifi => "wifi",
            MaterialIcon.Json => "file_json",
            MaterialIcon.DataUsage => "data_usage",
            MaterialIcon.JavaScript => "javascript",
            MaterialIcon.Analytics => "analytics",
            MaterialIcon.Insights => "insights",
            MaterialIcon.QueryStats => "query_stats",
            MaterialIcon.StackedBarChart => "stacked_bar_chart",
            MaterialIcon.Timeline => "timeline",
            MaterialIcon.TrendingUp => "trending_up",
            MaterialIcon.ShowChart => "show_chart",
            MaterialIcon.Web=>"web",
            MaterialIcon.AI=> "smart_toy",

            // Education & Learning
            MaterialIcon.School => "school",
            MaterialIcon.AutoStories => "auto_stories",
            MaterialIcon.LocalLibrary => "local_library",
            MaterialIcon.MenuBook => "menu_book",
            MaterialIcon.CastForEducation => "cast_for_education",
            MaterialIcon.Psychology => "psychology",
            MaterialIcon.Lightbulb => "lightbulb",

            // Certification & Awards
            MaterialIcon.Verified => "verified",
            MaterialIcon.MilitaryTech => "military_tech",
            MaterialIcon.EmojiEvents => "emoji_events",
            MaterialIcon.AwardStar => "workspace_premium",
            MaterialIcon.Star => "star",
            MaterialIcon.StarOutline => "star_outline",
            MaterialIcon.Diamond => "diamond",

            // Work & Business
            MaterialIcon.Work => "work",
            MaterialIcon.WorkHistory => "work_history",
            MaterialIcon.BusinessCenter => "business_center",
            MaterialIcon.Badge => "badge",
            MaterialIcon.Apartment => "apartment",
            MaterialIcon.Storefront => "storefront",
            MaterialIcon.Inventory => "inventory_2",
            MaterialIcon.Inventory2 => "inventory",
            MaterialIcon.CalendarMonth => "calendar_month",
            MaterialIcon.CalendarToday => "calendar_today",
            MaterialIcon.Schedule => "schedule",
            MaterialIcon.History => "history",
            MaterialIcon.HistoryEdu => "history_edu",

            // Media & Content
            MaterialIcon.Image => "image",
            MaterialIcon.PhotoLibrary => "photo_library",
            MaterialIcon.Videocam => "videocam",
            MaterialIcon.Movie => "movie",
            MaterialIcon.MusicNote => "music_note",
            MaterialIcon.Headphones => "headphones",
            MaterialIcon.PlayArrow => "play_arrow",
            MaterialIcon.Pause => "pause",
            MaterialIcon.Stop => "stop",
            MaterialIcon.VolumeUp => "volume_up",
            MaterialIcon.VolumeOff => "volume_off",
            MaterialIcon.Mic => "mic",
            MaterialIcon.CameraAlt => "camera_alt",
            MaterialIcon.Brush => "brush",
            MaterialIcon.Palette => "palette",
            MaterialIcon.Style => "style",
            MaterialIcon.Layers => "layers",
            MaterialIcon.AutoFixHigh => "auto_fix_high",
            MaterialIcon.Tune => "tune",
            MaterialIcon.SettingsSuggest => "settings_suggest",

            // UI & Layout
            MaterialIcon.Dashboard => "dashboard",
            MaterialIcon.GridView => "grid_view",
            MaterialIcon.ViewList => "view_list",
            MaterialIcon.ViewModule => "view_module",
            MaterialIcon.Widgets => "widgets",
            MaterialIcon.TableChart => "table_chart",
            MaterialIcon.Toc => "toc",
            MaterialIcon.Subject => "subject",
            MaterialIcon.Description => "description",
            MaterialIcon.Article => "article",
            MaterialIcon.NoteAlt => "note_alt",
            MaterialIcon.Assignment => "assignment",
            MaterialIcon.AssignmentInd => "assignment_ind",
            MaterialIcon.TaskAlt => "task_alt",
            MaterialIcon.PlaylistAddCheck => "playlist_add_check",

            // Social & People
            MaterialIcon.Person => "person",
            MaterialIcon.Group => "group",
            MaterialIcon.Groups => "groups",
            MaterialIcon.PersonAdd => "person_add",
            MaterialIcon.ThumbUp => "thumb_up",
            MaterialIcon.ThumbUpOffAlt => "thumb_up_off_alt",
            MaterialIcon.Favorite => "favorite",
            MaterialIcon.FavoriteBorder => "favorite_border",
            MaterialIcon.Diversity3 => "diversity_3",
            MaterialIcon.Handshake => "handshake",

            // File & Document
            MaterialIcon.Folder => "folder",
            MaterialIcon.FolderOpen => "folder_open",
            MaterialIcon.FolderShared => "folder_shared",
            MaterialIcon.FolderZip => "folder_zip",
            MaterialIcon.AttachFile => "attach_file",
            MaterialIcon.FilePresent => "file_present",
            MaterialIcon.Draft => "draft",
            MaterialIcon.TextSnippet => "text_snippet",
            MaterialIcon.RequestQuote => "request_quote",

            // E-commerce & Finance
            MaterialIcon.ShoppingCart => "shopping_cart",
            MaterialIcon.ShoppingBag => "shopping_bag",
            MaterialIcon.Payment => "payment",
            MaterialIcon.CreditCard => "credit_card",
            MaterialIcon.AccountBalance => "account_balance",
            MaterialIcon.CurrencyBitcoin => "currency_bitcoin",
            MaterialIcon.CurrencyExchange => "currency_exchange",
            MaterialIcon.ReceiptLong => "receipt_long",
            MaterialIcon.PriceCheck => "price_check",

            // Health & Fitness
            MaterialIcon.FitnessCenter => "fitness_center",
            MaterialIcon.MonitorHeart => "monitor_heart",
            MaterialIcon.EcgHeart => "ecg_heart",
            MaterialIcon.PulseAlert => "pulse_alert",
            MaterialIcon.Medication => "medication",
            MaterialIcon.LocalHospital => "local_hospital",

            // Nature & Environment
            MaterialIcon.DeviceThermostat => "device_thermostat",
            MaterialIcon.WbSunny => "wb_sunny",
            MaterialIcon.Nightlight => "nightlight",
            MaterialIcon.Thunderstorm => "thunderstorm",
            MaterialIcon.WaterDrop => "water_drop",
            MaterialIcon.Park => "park",
            MaterialIcon.Eco => "eco",
            MaterialIcon.EnergySavingsLeaf => "energy_savings_leaf",

            // Miscellaneous
            MaterialIcon.Home => "home",
            MaterialIcon.HomeMax => "home_max",
            MaterialIcon.Place => "place",
            MaterialIcon.Map => "map",
            MaterialIcon.Explore => "explore",
            MaterialIcon.Flight => "flight",
            MaterialIcon.Hotel => "hotel",
            MaterialIcon.Restaurant => "restaurant",
            MaterialIcon.LocalCafe => "local_cafe",
            MaterialIcon.SportsEsports => "sports_esports",
            MaterialIcon.Casino => "casino",
            MaterialIcon.Toys => "toys",
            MaterialIcon.Celebration => "celebration",
            MaterialIcon.RocketLaunch => "rocket_launch",
            MaterialIcon.TravelExplore => "travel_explore",
            MaterialIcon.Stars => "stars",
            MaterialIcon.Sparkles => "sparkles",
            MaterialIcon.AutoAwesome => "auto_awesome",
            MaterialIcon.Bolt => "bolt",
            MaterialIcon.FlashOn => "flash_on",
            MaterialIcon.Power => "power",
            MaterialIcon.BatteryFull => "battery_full",
            MaterialIcon.Timer => "timer",
            MaterialIcon.Alarm => "alarm",
            MaterialIcon.Speed => "speed",
            MaterialIcon.Scale => "scale",
            MaterialIcon.Balance => "balance",
            MaterialIcon.Gavel => "gavel",
            MaterialIcon.Fingerprint => "fingerprint",
            MaterialIcon.Face => "face",
            MaterialIcon.EyeTracking => "eye_tracking",
            MaterialIcon.Scan => "scan",
            MaterialIcon.QrCode => "qr_code",
            MaterialIcon.Barcode => "barcode",
            MaterialIcon.Link => "link",
            MaterialIcon.LinkOff => "link_off",
            MaterialIcon.Http => "http",
            MaterialIcon.Https => "https",
            MaterialIcon.WifiTethering => "wifi_tethering",
            MaterialIcon.Bluetooth => "bluetooth",
            MaterialIcon.Nfc => "nfc",
            MaterialIcon.Usb => "usb",
            MaterialIcon.Hdmi => "hdmi",
            MaterialIcon.Cable => "cable",
            MaterialIcon.Headset => "headset",
            MaterialIcon.ControllerGen => "controller_gen",
            MaterialIcon.Puzzle => "puzzle",
            MaterialIcon.Extension => "extension",
            MaterialIcon.ExtensionOff => "extension_off",

            _ => "help"
        };
    }
}
