namespace Portfolio.Models.Enums
{
    public enum MaterialIcon
    {
        // Navigation & Arrows
        ArrowBack,
        ArrowForward,
        ArrowDownward,
        ArrowUpward,
        ChevronRight,
        ChevronLeft,
        ExpandMore,
        ExpandLess,
        Menu,
        Close,
        OpenInNew,

        // Actions
        Check,
        CheckCircle,
        Add,
        Remove,
        Delete,
        Edit,
        Save,
        Refresh,
        Settings,
        Search,
        FilterList,
        Sort,
        Download,
        Upload,
        Share,
        CopyAll,
        ContentPaste,
        Visibility,
        VisibilityOff,

        // Communication
        Email,
        Chat,
        Notifications,
        NotificationsActive,
        Send,
        Phone,
        LocationOn,
        Language,
        Public,

        // Status & Feedback
        Info,
        Warning,
        Error,
        Success,
        Pending,
        HourglassEmpty,
        CheckCircleOutline,
        WarningAmber,
        ErrorOutline,
        Cancel,
        Block,
        Web,
        // Tech & Development
        Code,
        Terminal,
        Memory,
        Storage,
        Cloud,
        CloudUpload,
        CloudDownload,
        Database,
        Server,
        Api,
        Hub,
        NetworkNode,
        Security,
        Shield,
        Key,
        Lock,
        LockOpen,
        BugReport,
        Build,
        Engineering,
        SmartToy,
        Devices,
        Monitor,
        Smartphone,
        Laptop,
        DesktopMac,
        Router,
        Wifi,
        Json,
        DataUsage,
        JavaScript,
        Analytics,
        Insights,
        QueryStats,
        StackedBarChart,
        Timeline,
        TrendingUp,
        ShowChart,

        // Education & Learning
        School,
        AutoStories,
        LocalLibrary,
        MenuBook,
        CastForEducation,
        Psychology,
        Lightbulb,

        // Certification & Awards
        Verified,
        MilitaryTech,
        EmojiEvents,
        AwardStar,
        Star,
        StarOutline,
        Diamond,

        // Work & Business
        Work,
        WorkHistory,
        BusinessCenter,
        Badge,
        Apartment,
        Storefront,
        Inventory,
        Inventory2,
        CalendarMonth,
        CalendarToday,
        Schedule,
        History,
        HistoryEdu,

        // Media & Content
        Image,
        PhotoLibrary,
        Videocam,
        Movie,
        MusicNote,
        Headphones,
        PlayArrow,
        Pause,
        Stop,
        VolumeUp,
        VolumeOff,
        Mic,
        CameraAlt,
        Brush,
        Palette,
        Style,
        Layers,
        AutoFixHigh,
        Tune,
        SettingsSuggest,

        // UI & Layout
        Dashboard,
        GridView,
        ViewList,
        ViewModule,
        Widgets,
        TableChart,
        Toc,
        Subject,
        Description,
        Article,
        NoteAlt,
        Assignment,
        AssignmentInd,
        TaskAlt,
        PlaylistAddCheck,

        // Social & People
        Person,
        Group,
        Groups,
        PersonAdd,
        ThumbUp,
        ThumbUpOffAlt,
        Favorite,
        FavoriteBorder,
        Diversity3,
        Handshake,

        // File & Document
        Folder,
        FolderOpen,
        FolderShared,
        FolderZip,
        AttachFile,
        FilePresent,
        Draft,
        TextSnippet,
        RequestQuote,

        // E-commerce & Finance
        ShoppingCart,
        ShoppingBag,
        Payment,
        CreditCard,
        AccountBalance,
        CurrencyBitcoin,
        CurrencyExchange,
        ReceiptLong,
        PriceCheck,

        // Health & Fitness
        FitnessCenter,
        MonitorHeart,
        EcgHeart,
        PulseAlert,
        Medication,
        LocalHospital,

        // Nature & Environment
        DeviceThermostat,
        WbSunny,
        Nightlight,
        Thunderstorm,
        WaterDrop,
        Park,
        Eco,
        EnergySavingsLeaf,

        // Miscellaneous
        Flutter,
        HTML,
        CSS,
        AI,

        Home,
        HomeMax,
        Place,
        Map,
        Explore,
        Flight,
        Hotel,
        Restaurant,
        LocalCafe,
        SportsEsports,
        Casino,
        Toys,
        Celebration,
        RocketLaunch,
        TravelExplore,
        Stars,
        Sparkles,
        AutoAwesome,
        Bolt,
        FlashOn,
        Power,
        BatteryFull,
        Timer,
        Alarm,
        Speed,
        Scale,
        Balance,
        Gavel,
        Fingerprint,
        Face,
        EyeTracking,
        Scan,
        QrCode,
        Barcode,
        Link,
        LinkOff,
        Http,
        Https,
        WifiTethering,
        Bluetooth,
        Nfc,
        Usb,
        Hdmi,
        Cable,
        Headset,
        ControllerGen,
        Puzzle,
        Extension,
        ExtensionOff
    }
}
